### ISSUE TITLE
Wizard Titles showing up on the wrong pages

### ISSUE THREAD

**Issue by bemoore** [dominicbarnes/jWizard#1]
Great piece of code !

In Version 1.0, for the titles to work properly, you need to change the line 

$title.text(this.element.find(".jw-step:not(:visible)").attr("title"));
to
$title.text(this.element.find(".jw-step:visible").attr("title"));

as otherwise the wrong titles appear on the Wizard pages.

Bob

/**
         \* @private
         \* @description Updates the title
         \* @return void
         */
        _updateTitle: function(bIsFirstStep) {
            var $title = this.element.find(".jw-title");

```
        if (!bIsFirstStep) {
            this._effect($title, "title", "hide", "hide");
        }

        //$title.text(this.element.find(".jw-step:not(:visible)").attr("title"));
        //bemoore: Fixed wizard titles bug here by commenting out above line and replacing with this one
        $title.text(this.element.find(".jw-step:visible").attr("title"));

        if (!bIsFirstStep) {
            this._effect($title, "title", "show", "show");
        }

    },
```

**Comment by dominicbarnes** [comment]
Wow, how I missed that is beyond me... :S

**Comment by bemoore** [comment]
I thought I was doing something stupid for a while, as everything else worked so well :)
