### ISSUE TITLE
IE 7/8 support

### ISSUE THREAD

**Issue by TK11703** [dominicbarnes/jWizard#13]
I've tried using jQuery 1.4x, 1.5x, and 1.6x along with IE 7/8, but the plugin does not appear to be compatible. IE9 has no problems, but the percentage of IE9 vs IE7/8 is too huge to leave those users out. I've traced the problem down to what I believe is the button panel creation. Commenting out that part and it work, but no buttons.

**Comment by dominicbarnes** [comment]
Sorry about that, I was using jQuery to create elements dynamically via $("<button>", { ... props ...}); which apparently is severely broken in IE. I have refactored the code to avoid using props, and now appears to work in IE8 on WinXP. Please let me know if your testing reflects that. (please download the latest version from GitHub, I'll be uploading this change to jQuery Plugins asap)

**Comment by TK11703** [comment]
Dominic,
Looks much better in IE 7/8 now! Firefox 3.6 is good. 
I was using jQuery 1.5.x and UI 1.8.12 and it is good to go.
