### ISSUE TITLE
jQuery 1.6

### ISSUE THREAD

**Issue by TK11703** [dominicbarnes/jWizard#14]
Dominic,
I get some funny things when I use jQuery 1.6 and UI 1.8.12.
For IE using 1.6, the wizard looks almost normal, but the grey gradient on the title and button area is missing. When I use FF3.6, same gradient is missing, and all the navigation buttons are being displayed all the time.

**Comment by dominicbarnes** [comment]
Hmmm, I haven't had the time to work on jQuery 1.6 support yet, but that should be coming pretty soon.

**Comment by TK11703** [comment]
Cool, hopefully it won't include too much change for you.

**Comment by w3dot0** [comment]
Take a look at http://bugs.jquery.com/ticket/9150 - you will need to replace "className" with "class" to make jWizard work  with JQuery 1.6.

**Comment by TK11703** [comment]
Good catch... yeah that looks like a good recommendation.

**Comment by dominicbarnes** [comment]
I'm writing up a lot of tests right now to verify everything works, but so far my tests show that the [latest release](http://plugins.jquery.com/jWizard/) should be compatible with jQuery 1.6 and above. My test coverage isn't very high yet, but I will be working hard on improving it over the next few releases.
