### ISSUE TITLE
cancelHide not working

### ISSUE THREAD

**Issue by sederek** [dominicbarnes/jWizard#19]
Hi,

When I use cancelHide=true --> plugin makes a button like this:

button type="button" class="ui-state-default ui-corner-all jw-button-cancel jw-priority-secondary ui-button ui-widget ui-button-text-icon-primary" ui-helper-hidden"="" role="button" aria-disabled="false"><span class="ui-button-icon-primary ui-icon ui-icon-circle-close"></span><span class="ui-button-text">Cancel</span></button

It doesn't add or remove "ui-helper-hidden" CSS class, it makes this weirdness --> ui-helper-hidden"=""

**Comment by darryljamesheath** [comment]
This only seems to happen when using the minified file.  Suggests that the problem could be with the minification process or the minified file could be out of sync maybe?

**Comment by dominicbarnes** [comment]
This should be resolved with the [latest release](http://plugins.jquery.com/jWizard/).
