### ISSUE TITLE
Activate / deactivate Bind Error in IE

### ISSUE THREAD

**Issue by aaron-d-hunt** [dominicbarnes/jWizard#2]
When I bind an activate / deactivate function, it gets called anytime focus is off the steps div. Example: I have a select box in one step, if I click it to open it, I get my alert that the step is deactivated without clicking the next button. Any help would be greatly appreciated.

**Comment by dominicbarnes** [comment]
Oh wow, I just discovered there are existing events in IE called "activate" and "deactivate"! (http://msdn.microsoft.com/en-us/library/ms533051(VS.85).aspx) As a result, any form elements inside the wizard will trigger this event, and it bubbles up to the steps themselves.

In that case, I'm going to have to rename these events. Thanks for the heads-up! Being a Linux guy myself, I don't get to test IE as thoroughly as I should.

Thanks, a new commit will be coming soon

**Comment by dominicbarnes** [comment]
All right, check out the latest batch of commits, you will find your change there :)
