### ISSUE TITLE
Turning off tool tips...

### ISSUE THREAD

**Issue by cpsrac** [dominicbarnes/jWizard#22]
How do you remove or turn off the tool tip which pops up at the mouse pointer which show which step your on?

I have looked though the .js file looking for clues as what is responsible, but am to green to recognize.

**Comment by choi830** [comment]
The tool tip is caused by the "title" attribute\ in the fieldset tags. The Jwizard js file adds them to the fieldset tages. Just use Jquery to remove the "title attribute"

**Comment by cpsrac** [comment]
Thanks cgoi830,

I did as you suggested, it did remove the tooltips, but it also removed the title at the top of the Wizard page. The way I have setup the wizard I'm using the title at the top of the page, which uses the fieldset tag. I just want to kill the tooltips.

Maybe change the opacity for just the mouse over the fieldset area, which is what I'm trying to remove without destroying the title at the top of the wizard.

I have searched high and low on the web but still no luck. Any other suggestions would be very welcomed.

**Comment by aliuk2012** [comment]
Hi, Having had a look at the ourse Ithink it would be good to provide the developer a choice of tags to use perhap a data attribute? Something like data-jwizard-title="title1" and then instead of picking up .attr('title') .data('jwizard-title') could be used. I'm happy to knock up an example or a patch for the repo.

**Comment by dominicbarnes** [comment]
As of the [latest release](http://plugins.jquery.com/jWizard/), you can use `data-title` in place of `title`. (`title` will be checked for first, so it will take priority)

**Comment by aliuk2012** [comment]
Dominic I still think you should go with data-jwizard-title, the reason is that there less chance of there being another plugin or even the developer having another data-title on their page which would clash with jWizards one. Maybe not directly with jWizard but perhaps from their side.

**Comment by dominicbarnes** [comment]
Fair enough, I will include this change as part of the next release.

**Comment by cpsrac** [comment]
Here is a sniplet of the code I used to hide tool tips. It works great but I'm sure there is a better method.

```
    //------Hide Title of fieldsets
     var tempTitle = "";
     $('fieldset[title]').hover(
        function(e){
             e.preventDefault();
             tempTitle = $(this).attr('title');

             $(this).attr('title', '');
        }
       ,
       function() {
           $(this).attr('title', tempTitle);
       }
     );

    //------Hides titles of additional tags I created within a fieldset
    var tempTitle2 = "";
    $('h2.sliderLabel[title], div.infoHelpButton[title], div p.infoTxt[title]').hover( 
        function(e){
             e.preventDefault();
             tempTitle2 = $(this).attr('title');

             $(this).attr('title', '');
        }
       ,
       function() {
           $(this).attr('title', tempTitle2);
       }
    );
```

**Comment by dominicbarnes** [comment]
The `data-jwizard-title` attribute is now in place.
