### ISSUE TITLE
Demo website not working

### ISSUE THREAD

**Issue by crdesai** [dominicbarnes/jWizard#23]
dominicbarnes.us/jWizard is not working. Please provide a new link for the demos or fix the link.

Thanks

**Comment by alfredwester** [comment]
The demo still doesn't work... It would be great if you fixed the problem so people could test the jWizard... It's a really good wizard!

Thank you

**Comment by dominicbarnes** [comment]
The site has been reborn as [dbarnes.info/jWizard](http://dbarnes.info/jWizard). Sorry about the old site going down without notice :S
