### ISSUE TITLE
Refactor for Newer Versions of jQuery UI

### ISSUE THREAD

**Issue by dominicbarnes** [dominicbarnes/jWizard#25]
1.9 and 1.10 are out, update to work with both of them

**Comment by dominicbarnes** [comment]
The latest release should be compatible with 1.9.0+

**Comment by aliuk2012** [comment]
Is it backwards compatible? I'm assuming not because jQuery UI 1.8 does not have _hover

**Comment by dominicbarnes** [comment]
No, it is not backwards-compatible with 1.8.x anymore.

**Comment by aliuk2012** [comment]
Arr, thats a shame it is possible to have/keep a version that is 1.8 compatible because I'm sure there maybe others like me who cannot upgrade their ui versions as often as they are released.

**Comment by dominicbarnes** [comment]
I'll do my best, if I'm able to simplify as much as I hope, backwards-compatibility should not be a problem. I've neglected this code for a long time, so I'm having to re-acquaint myself with everything, including my sloppy coding. (especially since back then I had no concept of automated testing whatsoever lol)

I know a lot of people have found this widget useful, so my hope is that by adding automated testing (including automatically swapping in and out various combinations of jQuery/jQuery UI) then I can more quickly churn out releases and features.

Thanks for your patience :)
