### ISSUE TITLE
Add Unit Tests and Build Step

### ISSUE THREAD

**Issue by dominicbarnes** [dominicbarnes/jWizard#27]
Use phantomjs-mocha as a test-runner, along with grunt.js as a build step.

**Comment by aliuk2012** [comment]
Could you provide some guidance or tips? I used Github on Windows. I installed node js and used uglify to minify but apart from that I'm relatively new to this and I'm keen to help out.

**Comment by dominicbarnes** [comment]
I'll set up the build process and unit tests, since I already have a way in mind. I will probably need tests to cover each of the bug reports once I finish that.

I'll get the basics set up right away and report back :)

**Comment by dominicbarnes** [comment]
For those interested, I've added the `feature/build-process` branch (using [Git Flow](https://github.com/nvie/gitflow))

I'll be writing my tests with [mocha](http://visionmedia.github.com/mocha/), the runner will be [mocha-phantomjs](https://github.com/metaskills/mocha-phantomjs), and the assertion libraries will be [expect.js](https://github.com/LearnBoost/expect.js) and [jquery.expect.js](https://github.com/Codecademy/jquery-expect)

I will eventually be adding [Grunt](https://github.com/Codecademy/jquery-expect) to handle the build process, along with linting/minifying/tests/etc.

**Comment by dominicbarnes** [comment]
The test/build environment I have described above is now in place.

**Comment by aliuk2012** [comment]
Hi Dominic,
I really like to contribute to your project but I feel like I lack the skills with all the bits and pieces you've added recently. Do you have any tutorials or sites you could recommend? 

P.S I think the minified version of 1.7.0 is still referring to 1.6.2 as there is still the "Cancel" button beign displayed on the first step bug.

**Comment by dominicbarnes** [comment]
Yeah, until I release 1.7.1, you'll need to minify the original script yourself. Sorry about that :(

As far as tutorials, I would just read the documentation for each of the respective projects and work on adding tests to jWizard. I'll be more than happy to help give you some pointers along the way while you learn.
