### ISSUE TITLE
Jump to lastStep finish button error

### ISSUE THREAD

**Issue by xinaun** [dominicbarnes/jWizard#3]
By using any of the "jump" methods like:
$("#jWizard").jWizard("lastStep");
the "finish" button does not show up and the "next" button is still there.

**Comment by dominicbarnes** [comment]
I have not been able to recreate your described problem. Could you try out the latest version (just committed) and see if you are still having an issue. If so, please post any source code and further descriptions. Thanks :)

**Comment by xinaun** [comment]
I am sorry my report missed the necessary context as I know now. I could figure out what the problem is.

In order to skip some wizard pages I bound a jump method to the activate event of a page. This causes errors because the two page changes interfere with each other. So the buttons are changed twice but in the wrong order.

This use case might be very special, but it can be solved by adapting the _changeStep function slightly. If the two calls 
    nextStep.trigger("activate"); 
are merged and moved to the very end of the _changeStep function everything works fine.
Thank you for the reply.

**Comment by dominicbarnes** [comment]
Would you mind sending me your source code? I may be able to merge it in as a patch. :)
