### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cpsrac** [dominicbarnes/jWizard#31]
Option for jwizard to expand and contract vertically depending on content.
slideDown / slideUp animation to fit content on page change.

Option to fade content on page change.
fadeTo animation maybe?

My personal project I have modified the css to allow vertical expansion minus the animation, but would be more convenient if it where integrated option in the js

**Comment by dominicbarnes** [comment]
You should be able to control this, at least in a basic way, via the `effects` configuration options.

If not, I'm going to eventually be refactoring the entire transitions code that should make it much more flexible.

**Comment by dominicbarnes** [comment]
I'll close this, let me know if setting the effects options via configuration turns out to not be a viable option.
