### ISSUE TITLE
next or bind 'jwizardchangestep' not work

### ISSUE THREAD

**Issue by jotapdiez** [dominicbarnes/jWizard#32]
I have a situation that I need to make an internal submit when 'next' is clicked on the first step, so I overwrite the option next with my code:

``` javascript
$('#wizard').jWizard({
    next: function(event, ui) {
        alert("next");
        }
});
```

but the alert never shown.

So, I use bind like this:

``` javascript
$('#wizard').jWizard().bind("jwizardchangestep", function (event, ui) {
alert("jwizardchangestep::ui.currentStepIndex="+ui.currentStepIndex);
});
```

but still not showing anything.

am I doing something wrong?

**Comment by dominicbarnes** [comment]
Are you using v2 yet?

**Comment by jotapdiez** [comment]
According with jquery.jWizard.js:

``` javascript
/**
 * jWizard: a jQuery UI Wizard Widget
 *
 * @author Dominic Barnes <dominic@dbarnes.info>
 * @version 2.0.0
 */
```

**Comment by dominicbarnes** [comment]
Ok, as of v2, that event, and the `next` option, are no longer used. (See the [documentation](http://www.dbarnes.info/jWizard/#Events))

You can bind to individual steps for `stephide`, `stephidden`, `stepshow`, `stepshown`.

``` javascript
$("#step-1").on("stepshown", function () {
    alert("I'm on step #" + $(this).index());
});
```

If you need to monitor all steps, just bind to that same event on the wizard itself:

``` javascript
$("#wizard").on("stepshown", function () {
    alert("I'm on step #" + $(e.target).index());
});
```

**Comment by stef84** [comment]
Is there also a way to add form validation again? 

I'd like to fade (or hide) the "Next Step" Button until all Formfields at the current step have been filled out.

**Comment by dominicbarnes** [comment]
That will depend on how you implemented form validation, but yeah that's still very much possible.

If you're using a plugin like jquery.validation, bind your rules first, outside jWizard:

```
$("#step-1").validate({ ... });
```

After that, on the `stepshow` event you can hide the next button. (just reference the helper class `.jw-button-next`)

```
$("#step-1").on("stepshow", function (e) {
    $("#wizard .jw-button-next").hide();
});
```

Then, you bind to whatever events you need (`change`, `keyup`, etc) and check for the form's validity.

```
$("#step-1").on("change", function (e) {
    $("#wizard .jw-button-next").toggle($(this).valid());
});
```

This is kinda sloppy, but it should demonstrate enough to get you started. I've tried to get jWizard to take as little control as possible. This means that less is baked right in, but gives you a lot more flexibility to do things your way.
