### ISSUE TITLE
Reliance on jQuery UI

### ISSUE THREAD

**Issue by brgrz** [dominicbarnes/jWizard#35]
Don't you think we should implement a setting which would turn the jQuery UI CSS classes on and off? 

Would it make sense to make a plugin that works off jQuery UI and another one that works without it? What exactly do we need from jQuery UI besides the progressbar?

I don't think we need menu and buttons from jQuery UI.

**Comment by dominicbarnes** [comment]
I am using jQuery UI pretty heavily for managing the state of the wizard itself, including the whole widget lifecycle, event triggering, etc. Not that it can't be done without jQuery UI, but I'd have to create a good amount of boilerplate if it was only a jQuery plugin.

If I'm going to depart from jQuery UI, I'd rather move toward using [Component.js](https://github.com/component/component) instead. In fact, I'd really like to dump the entire reliance on jQuery, making jWizard an a unsuitable name. :P 

As far as turning the classes on and off, I was thinking that would be alright, but then realized that the other nested widgets like menu/button/progressbar all would still have their respective themeroller classes. Not only that, but it breaks convention as no other jQuery UI has this feature. Lastly, CSS makes it easy to override the styles anyway.

**Comment by brgrz** [comment]
ok then, for now it'll be better to stay with jquery UI. What I would do immediately is move menu out of the content, have it float around by itself just as the title bar is.

Also, I'd separate the title bar and progress bar and I'd stop pulling out the title altogether and hiding it within the step. I would leave the steps markup as author specifies it.

For instance, I like having the legend displayed right there inside the step.

see the attached screenshot for an example of UI I am working on

![wizard](https://f.cloud.github.com/assets/193816/460007/d4cec7cc-b411-11e2-95a2-ecf4993bb2dd.png)

**Comment by dominicbarnes** [comment]
I'm gonna close this, since the reliance upon jQuery UI itself will not change. If you want to address the menu specifically, open it as a separate issue.

While on the topic of a custom menu, you can probably implement one by disabling the built-in menu, creating your own external markup, monitoring the step events (step-show|shown|hide|hidden) and having your menu react accordingly.
