### ISSUE TITLE
no such method 'changeStep'

### ISSUE THREAD

**Issue by zecompadre** [dominicbarnes/jWizard#36]
jWizard  no such method 'changeStep' for widget instance 

when calling:

$w.jWizard("changeStep", 3);

**Comment by dominicbarnes** [comment]
Version 2.0 changes the API pretty drastically, use [$w.jWizard("step", ...)](https://github.com/dominicbarnes/jWizard/blob/master/src/wizard.js#L78) instead.

**Comment by zecompadre** [comment]
already found that solution

$w = $('#wizard');
var jWizard = $w.data('dbJWizard');
jWizard.step(0)

tks

**Comment by dominicbarnes** [comment]
`$w.jWizard("step", 0);` is the same as what you just showed.
