### ISSUE TITLE
finish button allways enable

### ISSUE THREAD

**Issue by zecompadre** [dominicbarnes/jWizard#38]
hi !

can it be done ?

tks

**Comment by aliuk2012** [comment]
Hi, 

I'm not sure Dominic would be able to do it but in my honest oppinion that just seems weird to have a "Finish" button always available through a wizard unless all the steps are optional?. The finish button is always on the page so you could write a bit of code that shows the button if you really need it. Maybe hook it into the change step event to always show it if hidden?

**Comment by dominicbarnes** [comment]
As of now, I have no intention of adding such a feature. Once we implement a finite state machine as the internals of the wizard, this will be _much_ easier to do.
