### ISSUE TITLE
Cancel button should return wizard to first step

### ISSUE THREAD

**Issue by FoxxMD** [dominicbarnes/jWizard#39]
I'm using your latest version inside of jquery dialogs -- im making the wizard act as a psuedo form instead of any actual submission. After clicking cancel the wizard does not reset to the first step(or reset at all for that matter).

**Comment by dominicbarnes** [comment]
I've removed the "magic" from the buttons. You should use the button configuration and an event handler to accomplish what you've described.

``` javascript
$("#wizard").jWizard({
    // set up the custom button types so the browser reacts as you expect
    buttons: {
        cancel: { type: "reset" },
        finish: { type: "submit" }
    },
    // bind to the cancel event to jump back to step 1
    // the form reset will now happen automatically because the button type is reset
    cancel: function (e, ui) {
        $(this).jWizard("first");
    }
});
```

**Comment by dominicbarnes** [comment]
I will include an "pseudo-form" example in the upcoming examples rewrite.
