### ISSUE TITLE
Changing step depending on the introduced data

### ISSUE THREAD

**Issue by SpArtA-zz** [dominicbarnes/jWizard#4]
Hi

First I would like to thank you for such a great wizard !
Then, I try to change which wizard page is shown when the user hit the "Next" button, depending on some data he has introduced. But I don't succeed. The goal it to move from step#1 to step#3 when hitting "Next", then from step#3 to step#1 when hitting previous, so that step2 is not shown.

When I make this:

```
    $('#step1').bind('onDeactivate', function(event) {
        console.debug('step1: onDeactivate');
        if (!isChangingStep) {
            isChangingStep = true;
            if (changeType == 1)
                $('#wizard').jWizard("changeStep", 3);
            isChangingStep = false;
        }
    });
```

It just shown the normal next page
The "isChangingStep" is here to avoid recursion

If I put the same code in the "onActivate" of step#2, then it works but I can make the difference between showing step #2 from the next button or from the back button. Becaure from the next mean I've to go to step 3, from the back means I've to go to step 1.

Do you have any idea to help me ?

Thanks a lot
Fabrice

**Comment by dominicbarnes** [comment]
Hi there, thanks for your kind words! :)

Try upgrading to the latest version of jWizard, I'm updating the documentation today, but onactivate/ondeactivate have been removed from the current and future versions of jWizard because of serious conflicts in IE.

So, first try using the renamed show and hide events. (I think you can leave off the word "on" at the beginning of your event type in the bind function)

**Comment by SpArtA-zz** [comment]
Ok I'll try
But not now because I'm close from a release. The work around is to put several hidden div in one step, and show the correct div depending on what the user introduced

Tx for your help and I'll give you feedback once I tried.

**Comment by dominicbarnes** [comment]
I've been putting off an overhaul of the events system of jWizard anyways, and this looks like a good opportunity for me to finally get this up-to-speed once and for all. I'll make sure to post here what changes I make and how they can be applied to your code. :)

**Comment by dominicbarnes** [comment]
Check out the newest version, as well as "examples/events.html" and you'll see my changes in regards to this :)
