### ISSUE TITLE
Use of class causes minimization issues

### ISSUE THREAD

**Issue by RKelln** [dominicbarnes/jWizard#40]
When you use class as a property yui-compressor fails to minimize the source. The following lines are problematic:

https://github.com/dominicbarnes/jWizard/blob/master/src/wizard.js#L257
https://github.com/dominicbarnes/jWizard/blob/master/src/wizard.js#L345
https://github.com/dominicbarnes/jWizard/blob/master/src/wizard.js#L346

The naive solution is to use "class" and options["class"] which allows the compressor to work, although I haven't full tested the code with that change it does seem to work.

**Comment by dominicbarnes** [comment]
Fixed with version 2.0.1
