### ISSUE TITLE
Crash ("n is undefined") if Finish button disabled - solved

### ISSUE THREAD

**Issue by saxopado** [dominicbarnes/jWizard#41]
Hello, while using your plugin, I ran into something.
If you want to disable the Finish button, you'll run into a plugin hang, with error "n is undefined" if using the minified version of jWizard, or reported on line 506 using the dev version, which relates to
<code>$finish.hide()</code>
with $finish being null (correctly, since you disabled it in the config options).

My quick and dirty solution was to as to apply a

<code> if ($finish!= null) $finish.hide(); </code>

line in each Case block in the  _updateButtons function.

There might be more elegant solutions, but I was in a hurry. Maybe do a higher level check on $finish, before entering the _updateButtons method? Add some sort of "no button" global flag to check?

Sorry I can't do a pull request right now, I have no experience on GitHub, I will if you request it.

Hope this helps.

**Comment by dominicbarnes** [comment]
Fixed with version 2.0.1

**Comment by saxopado** [comment]
great, thanks

Bye
Sacha

On Mon, Sep 23, 2013 at 3:25 AM, Dominic Barnes notifications@github.comwrote:

> Fixed with version 2.0.1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dominicbarnes/jWizard/issues/41#issuecomment-24895184
> .

## 

"And Saint Attila raised the hand grenade up on high, saying, 'Oh, Lord,
bless this thy hand grenade that with it thou mayest blow thy enemies to
tiny bits, in thy mercy.' And the Lord did grin, and people did feast upon
the lambs, and sloths, and carp, and anchovies, and orangutans, and
breakfast cereals, and fruit bats, and large --"
