### ISSUE TITLE
$.widget is undefined

### ISSUE THREAD

**Issue by mikebronner** [dominicbarnes/jWizard#44]
I'm getting the following error when including jquery.jWizard.js:

```
TypeError: 'undefined' is not a function (evaluating '$.widget')
```

Are there additional jquery UI plugins that need to be included apart from the jWizard plugin?

**Comment by dominicbarnes** [comment]
Are you including both jQuery and jQuery UI ahead of jWizard?

**Comment by dominicbarnes** [comment]
Most people will just include all of jQuery UI, but if you are creating a custom build, the minimum requirements are:
- Widget Factory
- Button
- Progress Bar
- Menu

**Comment by mikebronner** [comment]
Perfect! The issue was the order of the includes. I figured it didn't matter, expecting that any access to jQuery UI would be done after instantiation of the wizard object.
