### ISSUE TITLE
Unable to Declare Static Content

### ISSUE THREAD

**Issue by mikebronner** [dominicbarnes/jWizard#45]
I want to create a form that has a canvas that is shared throughout all steps, but it appears to think that the canvas is a step of its own.

```
<div id="wizard">
<canvas id="paint"></canvas>
<div title="Step 1"></div>
</div>
```

Is there any way to declare static content that remains visible throughout all the steps, or a specific work-around you might recommend?

Thanks!

**Comment by dominicbarnes** [comment]
Yeah, jWizard assumes all children of the root element are steps.

Is there any reason your `<canvas>` element can't exist outside the wizard element? Can you be more specific about what you're trying to accomplish?

**Comment by mikebronner** [comment]
It's purely for display purposes. The canvas is the main element of the form. At each step the user is given various options to manipulate the canvas. I would like the canvas to be displayed within the bounds of the wizard, but it doesn't have to be a child-object of the wizard from a coding perspective.

**Comment by dominicbarnes** [comment]
To me, it seems like you have 2 main options:
1. Use CSS to position that canvas element over your wizard. (kinda brittle idea, not my recommendation)
2. Use a separate canvas element for each step in your wizard. (yeah, kinda annoying, but arguably the most effective solution)

**Comment by mikebronner** [comment]
Good points. Yea, I've been thinking of those as well, and they all are prone to problems. There is a third possibility:
Insert the canvas into each step, shuffling it along with the form. Do the steps have callback functions I could make use of to do this, or do I just need to intercept the javascript events on the buttons?

Hey, thanks for your quick responses!

**Comment by dominicbarnes** [comment]
Actually, that's a great idea as well. There are events you can hook into, check out the [docs](http://www.dbarnes.info/jWizard/#events) for more details.

**Comment by mikebronner** [comment]
Perfect, this will work! I had looked the docs over before, but not from this viewpoint. I'll work on this tomorrow. Thanks again!
